# Generated by Django 3.1.4 on 2021-02-24 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20210224_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'items'},
        ),
    ]
