# Generated by Django 3.1.4 on 2021-01-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210113_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
