# Generated by Django 3.1.4 on 2021-02-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emial', models.EmailField(max_length=254)),
                ('subscribed', models.BooleanField(default=True)),
            ],
        ),
    ]
