# Generated by Django 3.1.4 on 2021-02-19 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribers',
            old_name='emial',
            new_name='email',
        ),
    ]
