# Generated by Django 3.1.4 on 2021-01-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_articlecomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomments',
            name='message',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
