# Generated by Django 3.1.4 on 2021-01-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_articlecomments_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomments',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
