# Generated by Django 3.1.4 on 2021-02-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20210224_0930'),
        ('blog', '0006_auto_20210113_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='common.Tags'),
        ),
    ]
